### ISSUE TITLE
Breaks with PyVirtualDisplay 1.0

### ISSUE THREAD

**Issue by vkbo** [The-Compiler/pytest-xvfb#22] opened 2020-05-27 20:00 UTC
I noticed all my builds were suddenly failing this afternoon, and tracked down the issue to PyVirtualDisplay just having released 1.0 a couple of hours ago. This version breaks `pytest-xvfb.py`. I temporarily fixed it by pinning PyVirtualDisplay to version 0.2.5.

Here's the output from my Travis log.
The whole thing is also here: https://travis-ci.com/github/vkbo/novelWriter/jobs/340639104
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/_pytest/main.py", line 193, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/_pytest/config/__init__.py", line 778, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pytest_xvfb.py", line 93, in pytest_configure
INTERNALERROR>     config.xvfb.start()
INTERNALERROR>   File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/pytest_xvfb.py", line 46, in start
INTERNALERROR>     self._virtual_display.cmd.extend(self.args)
INTERNALERROR> AttributeError: 'Display' object has no attribute 'cmd'
```

**Comment by The-Compiler** [comment] 2020-05-27 21:13
This seems to be caused by: https://github.com/ponty/PyVirtualDisplay/commit/20f6838e3870d11b75c8e30b08d225c1c640db96

From a (very) quick test, using `proc.cmd` instead of `cmd` there works, though tests are still acting a bit odd. I'll try to have a closer look later this week.

**Comment by vkbo** [comment] 2020-05-27 21:17
Yeah, I didn't have time to track it further as I'm in the middle of merging a bunch of bugfixes on my own project. But I'll be happy to look at it or test over the weekend.

**Comment by re4388** [comment] 2020-05-28 03:12
same issue here

**Comment by djhoese** [comment] 2020-05-29 13:43
Looks like this was fixed in PyVirtualDisplay 1.1 which was released yesterday and addressed in https://github.com/ponty/PyVirtualDisplay/issues/50. However, now with 1.1 I'm getting:

```
pyvirtualdisplay.abstractdisplay.XStartError: stop() is called before start().
```

So I filed https://github.com/ponty/PyVirtualDisplay/issues/51

**Comment by The-Compiler** [comment] 2020-05-29 14:25
@djhoese I'm not sure how https://github.com/ponty/PyVirtualDisplay/issues/50 would be related? I still can see this issue with PyVirtualDisplay 1.1, and that GitHub issue describes something else.

I also don't think https://github.com/ponty/PyVirtualDisplay/issues/51 is a PyVirtualDisplay bug - pytest-xvfb calls `.stop()` despite `.start()` having failed because of the exception. Here is the full output again:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 202, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/config/__init__.py", line 773, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pytest_xvfb.py", line 93, in pytest_configure
INTERNALERROR>     config.xvfb.start()
INTERNALERROR>   File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pytest_xvfb.py", line 46, in start
INTERNALERROR>     self._virtual_display.cmd.extend(self.args)
INTERNALERROR> AttributeError: 'Display' object has no attribute 'cmd'
Traceback (most recent call last):
  File "/home/florian/proj/pytest-xvfb/.tox/py27/bin/py.test", line 8, in <module>
    sys.exit(main())
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/config/__init__.py", line 84, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 243, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 238, in wrap_session
    config._ensure_unconfigure()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/_pytest/config/__init__.py", line 778, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pytest_xvfb.py", line 99, in pytest_unconfigure
    config.xvfb.stop()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pytest_xvfb.py", line 61, in stop
    self._virtual_display.stop()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 76, in stop
    self._obj.stop()
  File "/home/florian/proj/pytest-xvfb/.tox/py27/lib/python2.7/site-packages/pyvirtualdisplay/abstractdisplay.py", line 313, in stop
    raise XStartError("stop() is called before start().")
pyvirtualdisplay.abstractdisplay.XStartError: stop() is called before start().
```

**Comment by djhoese** [comment] 2020-05-29 14:36
>  I'm not sure how ponty/PyVirtualDisplay#50 would be related?

You're right. I was jumping around issues too fast and thought this issue was the same. Thanks for clearing things up and pointing out the correct exception.

**Comment by The-Compiler** [comment] 2020-05-29 15:41
Argh, looks like the 1.1 release changed how arguments are stored *again* with https://github.com/ponty/PyVirtualDisplay/commit/0aed78349f7bf7ca9b05d2b89f1a66eedf6c9397...

I wonder if we could use `pyvirtualdisplay.xvfb.XvfbDisplay` directly instead and perhaps override its `_cmd` method, though it looks that changed as well, see e.g. https://github.com/ponty/PyVirtualDisplay/commit/08f1fe625f18cf9c3b464c997b20e1930e713089.

With all those compatibility issues, I'm really starting to wonder if it was a good idea to use PyVirtualDisplay after all... (See #4 and #9).

**Comment by djhoese** [comment] 2020-05-29 16:33
> With all those compatibility issues, I'm really starting to wonder if it was a good idea to use PyVirtualDisplay after all... (See #4 and #9).

To be fair this is a jump from 0.2.x to 1.0. Maybe it'll be the last time things change a lot?

**Comment by vkbo** [comment] 2020-05-29 19:00
I'm sure the major version bump in part was due to the breaking of backwards compatibility, so it's sensible. Nothing is as bad as changing the API in a patch version, like the HDF5 library has done several times for instance.

**Comment by The-Compiler** [comment] 2020-05-29 19:29
I'm not bothered by the 1.0 break - more about the one in 1.1, but that might have been accidental.

**Closed** 2020-06-01 15:23 UTC

**Comment by The-Compiler** [comment] 2020-06-01 15:25
Hmm, looks like I somehow was mistaken above - *both* changes were part of PyVirtualDisplay 1.0. Not sure what went wrong during my tests then, those shouldn't have worked.

So I don't see a way to support versions between 1.0 and 1.2 (inclusive), but 1.3 added an `extra_args` argument: https://github.com/ponty/PyVirtualDisplay/issues/52.

I pushed a commit which fixes things, but also drops support for PyVirtualDisplay < 1.3. Does anyone still need support for older versions?

I'll take a break from opensource work for the rest of the week (call it at-home holidays if you will :laughing:), but I plan to take care of some remaining things and then release pytest-xvfb v2.0.0 next week.

**Comment by The-Compiler** [comment] 2020-06-09 17:19
pytest-xvfb v2.0.0 is [released](https://github.com/The-Compiler/pytest-xvfb/releases/tag/v2.0.0) now - thanks everyone for your patience, and let me know if any issues come up with the new release!

**Comment by thomasvanlankveld** [comment] 2020-10-21 15:05
Would it be possible to release v2.0.0 for Python 2.7?

We're stuck using Python 2.7 because ROS 2 is new, and we have a bunch of legacy code, but we'd really like to use this plugin! Right now we get this error with v1.2.0.

**Comment by The-Compiler** [comment] 2020-10-28 18:02
No, sorry - I'm not willing to maintain compatibility for a Python version which has been superseded for 12 years (give or take, I'm counting from the release of Python 3.0) and end-of-life since almost a year (after Python upstream already extending the EOL date by 5 years). Even pip (arguably the tool at the very bottom of the stack) will [drop Python 2 support](https://github.com/pypa/pip/issues/6148) in early 2021, and many others ([such as pytest itself](https://docs.pytest.org/en/stable/py27-py34-deprecation.html)) already did so in newer versions.

However, you should get away with pinning `PyVirtualDisplay` to `<1`, no?

**Comment by thomasvanlankveld** [comment] 2020-10-29 15:07
That worked, thanks!
